version: 2
updates: 
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      nuget-version-updates:
        applies-to: version-updates
        patterns: ["*"]
        update-types:
          - "minor"
          - "patch"
    
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
